In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
l1=[4,5,6,7,"steve",34,565,True]

In [8]:
a1 = np.array(l1)

In [9]:
a2 = np.array([[1,23,4],[2,4,5]])

In [10]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [11]:
a1.ndim

1

In [12]:
a2.ndim

2

In [13]:
a3.ndim

3

In [15]:
a1.size

8

In [16]:
a2.size

6

In [14]:
a3.size

9

In [17]:
a1.shape

(8,)

In [18]:
a2.shape

(2, 3)

In [19]:
a3.shape

(1, 3, 3)

In [20]:
np.random.randint(2,5)

2

In [21]:
np.random.randint(2,5)

2

In [22]:
np.random.randint(2,5)

3

In [26]:
np.random.randint(2,5, (3,4))

array([[2, 4, 4, 2],
       [4, 4, 2, 2],
       [3, 2, 3, 3]])

In [27]:
np.random.randint(2,5, (2, 3,4))

array([[[2, 4, 4, 4],
        [4, 3, 4, 3],
        [2, 2, 4, 2]],

       [[2, 2, 3, 4],
        [3, 4, 4, 4],
        [4, 3, 4, 4]]])

In [28]:
np.random.rand(2,3)

array([[0.35232466, 0.10720496, 0.12287526],
       [0.33972213, 0.33645544, 0.25548789]])

In [29]:
np.random.randint(2,3)

2

In [31]:
a4 = np.random.randn(4,4)

In [33]:
a4.reshape(8,2)

array([[-0.50275591,  0.50930349],
       [ 0.42857493, -0.87591046],
       [ 0.46038098, -0.86066899],
       [-0.15506546, -0.09751959],
       [-0.72777695, -0.79886793],
       [ 1.17512082,  0.55167021],
       [-0.97103613, -0.17248759],
       [-0.70432469,  2.06013859]])

In [34]:
a4.reshape(16,1)

array([[-0.50275591],
       [ 0.50930349],
       [ 0.42857493],
       [-0.87591046],
       [ 0.46038098],
       [-0.86066899],
       [-0.15506546],
       [-0.09751959],
       [-0.72777695],
       [-0.79886793],
       [ 1.17512082],
       [ 0.55167021],
       [-0.97103613],
       [-0.17248759],
       [-0.70432469],
       [ 2.06013859]])

In [35]:
a4.reshape(2,-1)

array([[-0.50275591,  0.50930349,  0.42857493, -0.87591046,  0.46038098,
        -0.86066899, -0.15506546, -0.09751959],
       [-0.72777695, -0.79886793,  1.17512082,  0.55167021, -0.97103613,
        -0.17248759, -0.70432469,  2.06013859]])

In [37]:
a4.reshape(1,2,1,4,2)

array([[[[[-0.50275591,  0.50930349],
          [ 0.42857493, -0.87591046],
          [ 0.46038098, -0.86066899],
          [-0.15506546, -0.09751959]]],


        [[[-0.72777695, -0.79886793],
          [ 1.17512082,  0.55167021],
          [-0.97103613, -0.17248759],
          [-0.70432469,  2.06013859]]]]])

In [38]:
a1[0]

'4'

In [39]:
a1[2:6]

array(['6', '7', 'steve', '34'], dtype='<U11')

In [41]:
a1[2:6:2]

array(['6', 'steve'], dtype='<U11')

In [42]:
a1[::-1]

array(['True', '565', '34', 'steve', '7', '6', '5', '4'], dtype='<U11')

In [43]:
a2[0]

array([ 1, 23,  4])

In [46]:
a2[:,1:]

array([[23,  4],
       [ 4,  5]])

In [47]:
a2[:,[1,2]]

array([[23,  4],
       [ 4,  5]])

In [48]:
a2[[0,1],[1,2]]

array([23,  5])

In [49]:
a2[[0,1],1:]

array([[23,  4],
       [ 4,  5]])

In [50]:
a5= np.random.randint(2,19,(6,5))

In [51]:
a5[a5>14]

array([18, 16, 15, 18, 17])

In [52]:
a5

array([[10, 18,  4,  9, 16],
       [13,  2,  9, 11,  3],
       [15, 13,  2, 18,  2],
       [17,  7,  7,  7,  4],
       [ 9,  9, 13,  2,  4],
       [ 2,  5, 10, 14,  5]])

In [53]:
a5[0,1]

18

In [54]:
a5[0,1]=100

In [55]:
a5

array([[ 10, 100,   4,   9,  16],
       [ 13,   2,   9,  11,   3],
       [ 15,  13,   2,  18,   2],
       [ 17,   7,   7,   7,   4],
       [  9,   9,  13,   2,   4],
       [  2,   5,  10,  14,   5]])

In [61]:
a6 = np.random.randint(0,3,(3,3))

In [60]:
a7= np.random.randint(0,3,(3,3))

In [62]:
a6*a7

array([[1, 4, 2],
       [0, 0, 0],
       [0, 0, 0]])

In [63]:
a6

array([[1, 2, 1],
       [0, 0, 0],
       [0, 2, 1]])

In [64]:
a7

array([[1, 2, 2],
       [0, 0, 2],
       [0, 0, 0]])

In [65]:
a6@a7

array([[1, 2, 6],
       [0, 0, 0],
       [0, 0, 4]])

In [66]:
np.array([[1,2],[3,4]])@np.array([[1,2,4],[6,1,1]])

array([[13,  4,  6],
       [27, 10, 16]])

In [67]:
a6+100

array([[101, 102, 101],
       [100, 100, 100],
       [100, 102, 101]])

In [68]:
a6*2

array([[2, 4, 2],
       [0, 0, 0],
       [0, 4, 2]])

In [69]:
a6/0

C:\Users\evens\AppData\Local\Temp\ipykernel_2804\1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\evens\AppData\Local\Temp\ipykernel_2804\1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, inf, inf],
       [nan, nan, nan],
       [nan, inf, inf]])

In [70]:
a6**3

array([[1, 8, 1],
       [0, 0, 0],
       [0, 8, 1]], dtype=int32)

In [71]:
a8 = np.zeros((4,4))

In [72]:
a9= np.ones((4,5))

In [73]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

##### Broadcasting

In [74]:
a9 + np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [75]:
a9 + np.array([1,2,3,4])

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [76]:
a9 + np.array([1,2,3,4]).T

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [79]:
np.array([1,2,3,4]).shape

(4,)

In [80]:
np.array([1,2,3,4]).T.shape

(4,)

In [81]:
np.array([1,2,3,4]).T

array([1, 2, 3, 4])

In [82]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [83]:
np.array([[1,2,3,4]]).T.shape

(4, 1)

In [84]:
a9 + np.array([[1,2,3,4]]).T

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [85]:
np.sqrt(a5)

array([[ 3.16227766, 10.        ,  2.        ,  3.        ,  4.        ],
       [ 3.60555128,  1.41421356,  3.        ,  3.31662479,  1.73205081],
       [ 3.87298335,  3.60555128,  1.41421356,  4.24264069,  1.41421356],
       [ 4.12310563,  2.64575131,  2.64575131,  2.64575131,  2.        ],
       [ 3.        ,  3.        ,  3.60555128,  1.41421356,  2.        ],
       [ 1.41421356,  2.23606798,  3.16227766,  3.74165739,  2.23606798]])

In [86]:
np.exp(a5)

array([[2.20264658e+04, 2.68811714e+43, 5.45981500e+01, 8.10308393e+03,
        8.88611052e+06],
       [4.42413392e+05, 7.38905610e+00, 8.10308393e+03, 5.98741417e+04,
        2.00855369e+01],
       [3.26901737e+06, 4.42413392e+05, 7.38905610e+00, 6.56599691e+07,
        7.38905610e+00],
       [2.41549528e+07, 1.09663316e+03, 1.09663316e+03, 1.09663316e+03,
        5.45981500e+01],
       [8.10308393e+03, 8.10308393e+03, 4.42413392e+05, 7.38905610e+00,
        5.45981500e+01],
       [7.38905610e+00, 1.48413159e+02, 2.20264658e+04, 1.20260428e+06,
        1.48413159e+02]])

In [87]:
np.log10(a5)

array([[1.        , 2.        , 0.60205999, 0.95424251, 1.20411998],
       [1.11394335, 0.30103   , 0.95424251, 1.04139269, 0.47712125],
       [1.17609126, 1.11394335, 0.30103   , 1.25527251, 0.30103   ],
       [1.23044892, 0.84509804, 0.84509804, 0.84509804, 0.60205999],
       [0.95424251, 0.95424251, 1.11394335, 0.30103   , 0.60205999],
       [0.30103   , 0.69897   , 1.        , 1.14612804, 0.69897   ]])

In [90]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [91]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
np.arange(1.8,10.7,2.5)

array([1.8, 4.3, 6.8, 9.3])

In [93]:
np.linspace(2,3,num=50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [94]:
np.linspace(2,3,num=50,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [96]:
np.logspace(2,4,num=4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [97]:
np.logspace(2,4,num=6,base=10)

array([  100.        ,   251.18864315,   630.95734448,  1584.89319246,
        3981.07170553, 10000.        ])

In [98]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])