In [1]:
import pandas as pd

In [2]:
data = {'name':['sudh','krish','hitesh','tulesko'],
       'salary':[100,200,300,400],
       'mail_id':['sudh@ineuron.ai','krish@ineuron.ai','hitesh@ineuron.ai','tulesko@ineuron.ai'],
       'addr':['blr','blr','blr','mum']}

In [3]:
pd.DataFrame(data)

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [5]:
data1 = {'name':['sudh','krish','hitesh','tulesko','extra'],
       'salary':[100,200,300,400],
       'mail_id':['sudh@ineuron.ai','krish@ineuron.ai','hitesh@ineuron.ai','tulesko@ineuron.ai'],
       'addr':['blr','blr','blr','mum']}

In [6]:
pd.DataFrame(data1)

ValueError: All arrays must be of the same length

In [7]:
pd.DataFrame(data,columns=[0,1,2,3])

Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []

In [21]:
# df = pd.DataFrame(data,index=[4,5,6,7])
df = pd.DataFrame(data)

In [10]:
df.loc[5:6]

name  salary            mail_id addr
5   krish     200   krish@ineuron.ai  blr
6  hitesh     300  hitesh@ineuron.ai  blr

In [11]:
df.iloc[5:6]

Empty DataFrame
Columns: [name, salary, mail_id, addr]
Index: []

In [12]:
df.iloc[1:6]

name  salary             mail_id addr
5    krish     200    krish@ineuron.ai  blr
6   hitesh     300   hitesh@ineuron.ai  blr
7  tulesko     400  tulesko@ineuron.ai  mum

In [13]:
df.iloc[0:4]

name  salary             mail_id addr
4     sudh     100     sudh@ineuron.ai  blr
5    krish     200    krish@ineuron.ai  blr
6   hitesh     300   hitesh@ineuron.ai  blr
7  tulesko     400  tulesko@ineuron.ai  mum

In [14]:
pd.DataFrame(data,index=['kris','sudh','tulesko','hite'])

name  salary             mail_id addr
kris        sudh     100     sudh@ineuron.ai  blr
sudh       krish     200    krish@ineuron.ai  blr
tulesko   hitesh     300   hitesh@ineuron.ai  blr
hite     tulesko     400  tulesko@ineuron.ai  mum

In [15]:
data11={
    'pf_nu':[234,45,54465,656],
    'income_tax':[234,565,767,6778],
    'mobile_no':[234523,34535,454,5656],
    'courses':['ds','bigdata','web dev','blockchain']
}

In [16]:
df1 = pd.DataFrame(data11)

In [22]:
pd.concat([df,df1])

name  salary             mail_id addr    pf_nu  income_tax  mobile_no  \
0     sudh   100.0     sudh@ineuron.ai  blr      NaN         NaN        NaN   
1    krish   200.0    krish@ineuron.ai  blr      NaN         NaN        NaN   
2   hitesh   300.0   hitesh@ineuron.ai  blr      NaN         NaN        NaN   
3  tulesko   400.0  tulesko@ineuron.ai  mum      NaN         NaN        NaN   
0      NaN     NaN                 NaN  NaN    234.0       234.0   234523.0   
1      NaN     NaN                 NaN  NaN     45.0       565.0    34535.0   
2      NaN     NaN                 NaN  NaN  54465.0       767.0      454.0   
3      NaN     NaN                 NaN  NaN    656.0      6778.0     5656.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2     web dev  
3  blockchain

In [23]:
pd.concat([df,df1],axis=1)

name  salary             mail_id addr  pf_nu  income_tax  mobile_no  \
0     sudh     100     sudh@ineuron.ai  blr    234         234     234523   
1    krish     200    krish@ineuron.ai  blr     45         565      34535   
2   hitesh     300   hitesh@ineuron.ai  blr  54465         767        454   
3  tulesko     400  tulesko@ineuron.ai  mum    656        6778       5656   

      courses  
0          ds  
1     bigdata  
2     web dev  
3  blockchain

In [25]:
data2 = {'0':['sudh','krish','hitesh','tulesko'],
       '1':[100,200,300,400],
       '2':['sudh@ineuron.ai','krish@ineuron.ai','hitesh@ineuron.ai','tulesko@ineuron.ai'],
       '3':['blr','blr','blr','mum']}
data3={
    '1':[234,45,54465,656],
    '2':[234,565,767,6778],
    '3':[234523,34535,454,5656],
    '3':['ds','bigdata','web dev','blockchain']
}

In [26]:
df2=pd.DataFrame(data2)
df3=pd.DataFrame(data3)

In [27]:
pd.concat([df2,df3])

0      1                   2           3
0     sudh    100     sudh@ineuron.ai         blr
1    krish    200    krish@ineuron.ai         blr
2   hitesh    300   hitesh@ineuron.ai         blr
3  tulesko    400  tulesko@ineuron.ai         mum
0      NaN    234                 234          ds
1      NaN     45                 565     bigdata
2      NaN  54465                 767     web dev
3      NaN    656                6778  blockchain

In [28]:
data4 = {
    'emp_id':[101,102,103,104],
    'salary':[234,345,200,400],
    'pf':[23,34,56,78],
}

data5 = {
    'emp_id':[101,102,104,105],
    'mob_no':[2334,5656,767,878],
    'house_nu':[345,345,345,56]
}

In [29]:
df4 = pd.DataFrame(data4)
df5 = pd.DataFrame(data5)

In [30]:
pd.merge(df4,df5)

emp_id  salary  pf  mob_no  house_nu
0     101     234  23    2334       345
1     102     345  34    5656       345
2     104     400  78     767       345

In [31]:
pd.merge(df4,df5,how='left')

emp_id  salary  pf  mob_no  house_nu
0     101     234  23  2334.0     345.0
1     102     345  34  5656.0     345.0
2     103     200  56     NaN       NaN
3     104     400  78   767.0     345.0

In [32]:
pd.merge(df4,df5,how='right')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    2334       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [33]:
pd.merge(df4,df5,how='outer')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0  2334.0     345.0
1     102   345.0  34.0  5656.0     345.0
2     103   200.0  56.0     NaN       NaN
3     104   400.0  78.0   767.0     345.0
4     105     NaN   NaN   878.0      56.0

In [34]:
pd.merge(df4,df5,how='cross')

emp_id_x  salary  pf  emp_id_y  mob_no  house_nu
0        101     234  23       101    2334       345
1        101     234  23       102    5656       345
2        101     234  23       104     767       345
3        101     234  23       105     878        56
4        102     345  34       101    2334       345
5        102     345  34       102    5656       345
6        102     345  34       104     767       345
7        102     345  34       105     878        56
8        103     200  56       101    2334       345
9        103     200  56       102    5656       345
10       103     200  56       104     767       345
11       103     200  56       105     878        56
12       104     400  78       101    2334       345
13       104     400  78       102    5656       345
14       104     400  78       104     767       345
15       104     400  78       105     878        56

In [35]:
pd.merge(df4,df5,how='right',on='emp_id')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    2334       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [36]:
data6 = {
    'emp_id1':[101,102,103,104],
    'salary':[234,345,200,400],
    'pf':[23,34,56,78],
}

data7 = {
    'emp_id2':[101,102,104,105],
    'mob_no':[2334,5656,767,878],
    'house_nu':[345,345,345,56]
}

In [37]:
df6=pd.DataFrame(data6)
df7=pd.DataFrame(data7)

In [38]:
pd.merge(df6,df7)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [39]:
pd.merge(df6,df7,left_on='emp_id1',right_on='emp_id2')

emp_id1  salary  pf  emp_id2  mob_no  house_nu
0      101     234  23      101    2334       345
1      102     345  34      102    5656       345
2      104     400  78      104     767       345

In [4]:
data8 = {
    'emp_id':[101,102,103,104],
    'salary':[234,345,200,400],
    'pf':[23,34,56,78],
}

data9 = {
    'emp_id':[101,102,104,105],
    'salary':[234,345,200,400],
    'house_nu':[345,345,345,56]
}

In [5]:
df8=pd.DataFrame(data8)
df9=pd.DataFrame(data9)

In [6]:
pd.merge(df8,df9,on=['emp_id','salary'])

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [10]:
data10 = {
    'emp_id1':[101,102,103,104],
    'salary1':[234,345,200,400],
    'pf':[23,34,56,78],
}

data11 = {
    'emp_id2':[101,102,104,105,123],
    'salary2':[234,345,200,400,43],
    'house_nu':[345,345,345,56,234]
}

In [11]:
df10=pd.DataFrame(data10, index=['a','b','c','d'])
df11=pd.DataFrame(data11, index=['a','b','d','e','f'])

In [12]:
df10.join(df11)

emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23    101.0    234.0     345.0
b      102      345  34    102.0    345.0     345.0
c      103      200  56      NaN      NaN       NaN
d      104      400  78    104.0    200.0     345.0

In [14]:
dfSales = pd.read_csv('../July 30 Pandas/sales_data_final.csv')

In [15]:
def profit_flag(a):
    if a>0:
        return 'positive'
    else:
        return 'negative'

In [16]:
profit_flag(-45)

'negative'

In [17]:
profit_flag(45)

'positive'

In [18]:
dfSales['flag_profit']=dfSales['profit'].apply(profit_flag)

In [19]:
dfSales['flag_profit']

0        positive
1        positive
2        positive
3        negative
4        positive
           ...   
51285    positive
51286    positive
51287    positive
51288    positive
51289    negative
Name: flag_profit, Length: 51290, dtype: object

In [20]:
dfSales['len_cust_name']=dfSales['customer_name'].apply(len)

In [21]:
dfSales['len_cust_name']

0        15
1        11
2        13
3        12
4        11
         ..
51285    10
51286     9
51287    16
51288    13
51289    13
Name: len_cust_name, Length: 51290, dtype: int64

In [23]:
def quantity_flag(a):
    if a < 10:
        return 'low'
    elif a > 10 and a < 20:
        return 'medium'
    else:
        return 'high'

In [24]:
dfSales['flag_quantity']=dfSales['quantity'].apply(quantity_flag)

In [26]:
dfSales['flag_quantity'].value_counts()

low       50413
medium      601
high        276
Name: flag_quantity, dtype: int64

In [27]:
dfSales['square_quantity']=dfSales['quantity'].apply(lambda x:x**2)

In [28]:
dfSales[['quantity','square_quantity']].head(3)

quantity  square_quantity
0         2                4
1         3                9
2         4               16

In [30]:
    import numpy as np

In [31]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [32]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [33]:
np.array([[2,3,4],
         [4,5,6]])

array([[2, 3, 4],
       [4, 5, 6]])

In [34]:
np.array([[1,2,3,4],
         [2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [35]:
l = [[1, 2, 3, 4],
       [2, 3, 4, 5]]

In [36]:
l[0][0]

1

In [38]:
a = np.array([1, 2, 3, 4], ndmin=5)

In [39]:
a

array([[[[[1, 2, 3, 4]]]]])

In [40]:
arr = np.array([[1,2,4],[4,5,6],[7,8,9]])

In [41]:
arr

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr.ndim

2

In [43]:
np.random.randint(1,10,(4,4))

array([[4, 3, 3, 6],
       [8, 9, 3, 1],
       [1, 1, 6, 3],
       [5, 4, 3, 2]])

In [44]:
np.random.randint(1,10,(4,4,2))

array([[[1, 2],
        [6, 2],
        [2, 6],
        [6, 2]],

       [[2, 8],
        [9, 4],
        [3, 8],
        [2, 5]],

       [[8, 8],
        [3, 6],
        [8, 9],
        [6, 8]],

       [[2, 2],
        [9, 6],
        [7, 9],
        [2, 8]]])